Lesson Timer#
allrom/TestGuru pull request #18
Opened 2019-05-28 08:02 UTC by allrom

2019-05-28 10:47 UTC, psylone requested changes

2019-05-28 10:47 UTC, psylone commented on db/schema.rb
> +    t.boolean "timing", default: false
Достаточно одного поля со значением времени. Если в нём что-то есть, значит таймер установлен, если `nil`, значит тест без таймера.

2019-05-28 10:47 UTC, psylone commented on db/schema.rb
> +    t.datetime "lasting", default: '1970-01-01 00:00:00'
Будет лучше и проще хранить количество секунд отведённое на прохождение теста.

2019-05-28 10:47 UTC, psylone commented on config/application.rb
> +    # Disable ActiveRecord's time zone logic
Так лучше не делать.

2019-05-28 10:47 UTC, psylone commented on config/initializers/assets.rb
> +Rails.application.config.assets.precompile += %w( jquery.countdown.min.js jquery.plugin.min.js )
Зачем отдельно компилировать эти файлы, ведь ты уже добавил их в манифест.

2019-05-28 10:47 UTC, psylone commented on app/views/test_passages/show.html.erb
> +      var expiryDate = new Date('<%= @test_passage.to_be_completed_at %>'.replace(/\-/g, '\/').replace(/[T|Z]/g, ' '));
С секундами работать было бы проще. Основная идея в том чтобы хранить и работать с величиной в её базовом представлении, а там где нужно уже форматировать согласно требованиям. То есть в нашем случае мы бы в JS коде из секунд получали количество минут и секунд.

2019-05-28 10:47 UTC, psylone commented on app/views/test_passages/show.html.erb
> +  <script type="text/javascript">
Скрипт должен быть в ассетах, а не в ERB шаблоне.

2019-05-28 10:47 UTC, psylone commented on app/models/test_passage.rb
> +  def to_be_completed_at
Из названия метода не ясно что он возвращает. Я бы подумал, что возвращается объект времени.

2019-05-28 10:47 UTC, psylone commented on app/models/test_passage.rb
> +  def to_be_completed_at
Также это не совсем `completed`, скорее `expired`.

2019-05-28 10:47 UTC, psylone commented on app/views/test_passages/show.html.erb
> +  <script type="text/javascript">
JS можно отключить, тогда пользователь сможет продолжать прохождение теста, не смотря на окончание таймера, поэтому необходимо также на сервере делать проверку что время ещё не вышло.

Это можно сделать с помощью обратного вызова в контроллере прохождения тестов перед обработкой ответа на вопрос.

2019-05-31 09:09 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +      flash.now[:warning] = t('.expired')
помимо предупреждения, стоит пользователя перевести на страницу результатов

2019-05-31 09:09 UTC, BubuntuClu commented on app/helpers/admin/tests_helper.rb
> +			t('.test_lasting_else')
странный нейминг. он что означает?

2019-05-31 09:09 UTC, BubuntuClu commented on app/helpers/admin/tests_helper.rb
> +			t('.test_lasting')
отступы

2019-05-31 09:09 UTC, BubuntuClu commented on db/migrate/20190523212111_add_timing_to_tests.rb
> +class AddTimingToTests < ActiveRecord::Migration[5.2]
эта миграция еще не в мастер ветке, можно ее править, не обязательно делать миграцию на удаление этих полей в отдельном файле. ты локально можешь их убрать

2019-05-31 09:09 UTC, BubuntuClu commented on app/models/test.rb
> +  before_save :before_save_compute_test_seconds, on: %i[create, update] if %i[minutes, seconds].any?
мне кажется, проще было бы напрямую задавать значение длительности теста

2019-05-31 09:09 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    seconds = self.test.expire_in
`test.expire_in + created_at`

2019-05-31 09:09 UTC, BubuntuClu commented on app/models/user.rb
> +    def pick_by_level(difficulty_level)
лишний отступ

2019-05-31 09:09 UTC, BubuntuClu commented on app/views/admin/tests/_form.html.erb
> +    <%= form.number_field :minutes, min: 0, max: 59 %>&nbsp
а 60 минут я не могу указать?)

2019-05-31 13:54 UTC, merged