Lesson Associations In Models
allrom/TestGuru pull request #4
Opened 2019-02-06 21:54 UTC by allrom

2019-02-06 23:10 UTC, psylone requested changes
По диаграмме:

+ Логичней если у категории может не оказаться ни одного теста.
+ Эта же идея относится к тестам и ответам.

2019-02-06 23:10 UTC, psylone commented on app/models/test.rb
> Между Тестом и автором (Пользователем), который его создал.

Этой ассоциации нет.

2019-02-06 23:10 UTC, psylone commented on app/models/test.rb
Не забудь добавить её также в модель `User`.

2019-02-07 11:06 UTC, allrom commented on app/models/test.rb
Евгений, спасибо. В личные напрвил сообщение - кое -что уточнить для себя

2019-02-08 19:24 UTC, psylone approved these changes

2019-02-08 19:26 UTC, psylone commented on app/models/test.rb
Ответил.

2019-02-11 06:13 UTC, merged