Lesson Action_Controller
allrom/TestGuru pull request #6
Opened 2019-02-19 07:18 UTC by allrom

2019-02-19 09:31 UTC, BubuntuClu requested changes

2019-02-19 09:31 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @questions = Question.where(:test_id => @test.id)
`@questions = @test.questions`

2019-02-19 09:31 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    new_question = Question.create(new_question_params)
тебе вопрос надо привязать к тесту еще, так же учесть что тебе могут не дойти параметры с фронта
```
def create
  question = @test.questions.new(new_question_params)
  if question.save
      render good answer
  else
     render bad answer
  end
end
```

2019-02-19 09:31 UTC, BubuntuClu commented on app/views/questions/new.html.erb
> +<form action="/tests/:test_id/questions" method="post">
`/tests/:test_id/questions`
тут надо подставлять значение теста, в котором находишься. можно из `params` его достать

2019-02-19 09:31 UTC, BubuntuClu commented on app/views/questions/new.html.erb
> +    <label for="test-id">Test Id:</label>
тогда вот этого можно будет избежать, у тебя автоматически в ссылке будет указан id теста

2019-02-19 09:31 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    render plain: 'Question not found...'
добавь еще код ответа 404, сейчас будет надпись что вопрос не найден, но ответ будет 200

2019-02-19 09:31 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:body, :test_id)
при создании через ассоциацию тебе не надо `test_id` передавать. находишь объект в обратном вызове и уже в экшене используешь его

2019-02-20 10:34 UTC, psylone approved these changes

2019-02-20 10:34 UTC, psylone commented on app/controllers/questions_controller.rb
> +                    <p><%= @questions.pluck(:body).join("<br/>").html_safe %></p>'
Поскольку здесь всё рендерится внутри экшена можно использовать локальную переменную вместо инстанс переменной.

2019-02-20 10:34 UTC, psylone commented on app/views/questions/new.html.erb
> +    <input name="authenticity_token" value="<<%= form_authenticity_token %>" type="hidden">
```suggestion
    <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
```

2019-02-21 11:37 UTC, merged